// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKj2rV9w9Y3JS_-PaoMLLdXkvH3e2bSw4',
    appId: '1:749553349568:web:6e1075bcf5851128e5ce25',
    messagingSenderId: '749553349568',
    projectId: 'vitality-23966',
    authDomain: 'vitality-23966.firebaseapp.com',
    storageBucket: 'vitality-23966.firebasestorage.app',
    measurementId: 'G-YXHQRHXHZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvS9MoFLD2hRjFGnAo_lGQYLQpEyA-u0Q',
    appId: '1:749553349568:android:a75d6d932d1faf6ee5ce25',
    messagingSenderId: '749553349568',
    projectId: 'vitality-23966',
    storageBucket: 'vitality-23966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeNF6xQ6e7TYuKphTNr6hWZMcEdGHCNLM',
    appId: '1:749553349568:ios:2030de5b8f700437e5ce25',
    messagingSenderId: '749553349568',
    projectId: 'vitality-23966',
    storageBucket: 'vitality-23966.firebasestorage.app',
    iosBundleId: 'com.vitality.app.vitality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeNF6xQ6e7TYuKphTNr6hWZMcEdGHCNLM',
    appId: '1:749553349568:ios:2030de5b8f700437e5ce25',
    messagingSenderId: '749553349568',
    projectId: 'vitality-23966',
    storageBucket: 'vitality-23966.firebasestorage.app',
    iosBundleId: 'com.vitality.app.vitality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKj2rV9w9Y3JS_-PaoMLLdXkvH3e2bSw4',
    appId: '1:749553349568:web:659e13568ac997aee5ce25',
    messagingSenderId: '749553349568',
    projectId: 'vitality-23966',
    authDomain: 'vitality-23966.firebaseapp.com',
    storageBucket: 'vitality-23966.firebasestorage.app',
    measurementId: 'G-497PG3YHG2',
  );
}
